### PR TITLE
one approach to fix #258 and elegant #262

### LINKED ISSUE #258: first atwho-inserted gets removed when selecting text using CTRL+A
The first atwho-inserted tag gets removed when you select all the text using keyboard shortcut CTRL+A. 
It's broken when the line starts with the input but works if there is some text before the inputor.

Test case:
1. Type inputor "@user" to input box
2. Type some text
3. Type inputor "@user2" to input box
4. Press CTRL+a to select text

Result:
Text selecting fails, the first atwho-inserted tag is removed and cursor is placed before the second inputor
select

### PR DESCRIPTION
**Pull request by houd1ni**
Because of absence of other bad symptoms of reselecting code, based of ranges, I prefered just removing default handlers: remove and add Range, that, probably is less elegant way, but we can add own handler for CTRL events in future. More than, it fixes another found ctrl+a bugs, which I saw during debug. E.g. I couldn't select with ctrl+a after typing just "@jacob ", which, of course, has been generated by reselecting code.
Maybe, more beautiful way is creating something like '@vars' or '@pressed_btn' objects to handle that kind of variables, but now I prefered just delete them on the fly.
Tested in Chrome, ie11, mozilla.

### CODE REVIEW

**Comment by ichord** [comment]
You rock! @houd1ni . I will check it later.

**Comment by ichord** [comment]
@houd1ni you can [close issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

fix #258 , fix #262

**Comment by ichord** [comment]
oh..... I forgot that the element which has `contenteditable=false` can't be delete in firefox...

**Comment by houd1ni** [comment]
I'll make it deletable soon)

**Pull request merged**
