### PR TITLE
Added scrollDuration option

### PR DESCRIPTION
**Pull request by ttakuru88**
I wanted to disable the scroll animation, so I added a scrollDuration option.
This option controls the duration of the scroll animation.
The default value is 150ms.
If you set the value to falsy, then scrollTop is called instead of animate.

:smiley:

### CODE REVIEW

**Comment by ichord** [comment]
BTW. why you wanted to disable the scroll animation?!

**Comment by ttakuru88** [comment]
Thanks for the merge!!

Try out this demo.
When there are alot of items to choose, the scroll kinda gets messy and delayed when there are multiple scrolls(like holding down the down key).
I thought disabling the scroll animation would be user-friendly in some cases.

**Comment by ttakuru88** [comment]
Demo: http://hai3.net/dev/atjs.html

**Comment by ichord** [comment]
It's great. Thanks your pull request.

**Pull request merged**
